name: build

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - branch: development
            tag: DEVELOPMENT-SNAPSHOT-2024-02-08-a
            options: -Xswiftc "-I${env:SDKROOT}\usr\lib\swift_static\windows" -Xswiftc "-I${env:SDKROOT}\..\..\..\..\..\..\Toolchains\0.0.0+Asserts\usr\include"

    name: Swift ${{ matrix.tag }}

    steps:
      - uses: compnerd/gha-setup-swift@main
        with:
          tag: ${{ matrix.tag }}
          branch: ${{ matrix.branch }}

      - uses: actions/checkout@v3

      - uses: dsaltares/fetch-gh-release-asset@a40c8b4a0471f9ab81bdf73a010f74cc51476ad4 # v1.1.1
        with:
          repo: thebrowsercompany/firebase-cpp-sdk
          version: tags/20230921.0
          file: firebase-windows-amd64.zip

      - run: Expand-Archive -Path firebase-windows-amd64.zip -DestinationPath third_party/firebase-development
        shell: powershell

      - name: Build
        run: swift build -v ${{ matrix.options }}
